import React,{useState,useMemo,useRef}from'react';import{createRoot}from'react-dom/client';import{Download,Play,Square,RefreshCcw}from'lucide-react';import'./style.css';
const DEFAULT='SBER, LKOH, GAZP, TATN, GMKN, VTBR, RUAL, AFLT, NVTK, MOEX, YDEX, CASH';
function fmtPct(x){return x==null?'':(x*100).toFixed(2)+'%'}
function toCsv(rows,tickers){const h=['Date',...tickers];const lines=[h.join(',')];for(const r of rows){lines.push([r.date,...tickers.map(t=>r.returns[t]==null?'':(r.returns[t]*100).toFixed(6)+'%')].join(','))}return lines.join('\n')}
function download(name,text){const b=new Blob(['\ufeff'+text],{type:'text/csv;charset=utf-8;'});const u=URL.createObjectURL(b);const a=document.createElement('a');a.href=u;a.download=name;a.click();URL.revokeObjectURL(u)}
async function fetchTicker(ticker,from,till,signal){const r=await fetch(`/api/moex-history?ticker=${encodeURIComponent(ticker)}&from=${from}&till=${till}`,{signal});return r.json()}
function App(){const[tickersText,setTickersText]=useState(DEFAULT);const[from,setFrom]=useState('2024-01-01');const[till,setTill]=useState(new Date().toISOString().slice(0,10));const[status,setStatus]=useState([]);const[data,setData]=useState({});const[loading,setLoading]=useState(false);const ctrl=useRef(null);const tickers=useMemo(()=>[...new Set(tickersText.split(/[;,\s]+/).map(x=>x.trim().toUpperCase()).filter(Boolean))], [tickersText]);
const table=useMemo(()=>{const dates=new Set();for(const t of Object.keys(data))for(const p of data[t])dates.add(p.date);const ds=[...dates].sort();return ds.map(date=>{const prices={},returns={};for(const t of Object.keys(data)){const arr=data[t];const i=arr.findIndex(x=>x.date===date);if(i>=0){prices[t]=arr[i].close;returns[t]=i>0?arr[i].close/arr[i-1].close-1:0}}return{date,prices,returns}})},[data]);
async function load(){ctrl.current?.abort();const ac=new AbortController();ctrl.current=ac;setLoading(true);setData({});setStatus([]);const next={};for(const t of tickers){if(ac.signal.aborted)break;setStatus(s=>[...s,{ticker:t,msg:'загрузка...',type:'wait'}]);try{if(['CASH','RUB','MNYMKT'].includes(t)){const cashRows=[];let d=new Date(from);const end=new Date(till);while(d<=end){if(d.getDay()!==0&&d.getDay()!==6)cashRows.push({date:d.toISOString().slice(0,10),close:1});d.setDate(d.getDate()+1)}next[t]=cashRows;setStatus(s=>s.map(x=>x.ticker===t?{ticker:t,msg:'кэш 0%',type:'ok'}:x));continue}const j=await fetchTicker(t,from,till,ac.signal);if(j.ok&&j.rows?.length){next[t]=j.rows;setStatus(s=>s.map(x=>x.ticker===t?{ticker:t,msg:`${j.rows.length} дней, ${j.market}/${j.board}${j.requested&&j.requested!==j.ticker?` (${j.requested}→${j.ticker})`:''}`,type:'ok'}:x));}else{setStatus(s=>s.map(x=>x.ticker===t?{ticker:t,msg:j.error||'данные не найдены',type:'bad'}:x));}}catch(e){setStatus(s=>s.map(x=>x.ticker===t?{ticker:t,msg:e.name==='AbortError'?'остановлено':e.message,type:'bad'}:x));}setData({...next});}
setLoading(false)}
return <div className="wrap"><header><h1>MOEX Daily Return Parser</h1><p>Автоматическая загрузка дневных данных российских активов через серверный MOEX ISS API. CSV выгружает только Daily Return.</p></header><section className="panel"><label>Тикеры</label><textarea value={tickersText} onChange={e=>setTickersText(e.target.value)}/><div className="grid"><div><label>Дата от</label><input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></div><div><label>Дата до</label><input type="date" value={till} onChange={e=>setTill(e.target.value)}/></div></div><div className="buttons"><button onClick={load} disabled={loading}><Play size={18}/> Загрузить</button><button className="secondary" onClick={()=>ctrl.current?.abort()}><Square size={18}/> Остановить</button><button className="secondary" onClick={()=>{setData({});setStatus([])}}><RefreshCcw size={18}/> Сброс</button><button className="secondary" disabled={!table.length} onClick={()=>download('moex_daily_returns.csv',toCsv(table,Object.keys(data)))}><Download size={18}/> Скачать Daily Return CSV</button></div></section><section className="status"><h2>Статус</h2>{status.length===0?<p className="muted">Пока нет загрузки.</p>:status.map(s=><div className={s.type} key={s.ticker}>{s.type==='ok'?'✅':s.type==='bad'?'❌':'⏳'} <b>{s.ticker}</b>: {s.msg}</div>)}</section><section className="tablebox"><h2>Daily Return</h2>{table.length===0?<p className="muted">После загрузки здесь появятся дневные доходности.</p>:<table><thead><tr><th>Date</th>{Object.keys(data).map(t=><th key={t}>{t}</th>)}</tr></thead><tbody>{table.map(r=><tr key={r.date}><td>{r.date}</td>{Object.keys(data).map(t=><td key={t}>{fmtPct(r.returns[t])}</td>)}</tr>)}</tbody></table>}</section></div>}
createRoot(document.getElementById('root')).render(<App/>);
